travis:
  secure:
    BINSTAR_TOKEN: oUMU+M9YVeEEU32lZJTuKJlSzWK1EtLSJzZgusNOqmPt4ZnCjGC51zWIxN+LUeOasnt+yCdd5mp7gntwd8xLZmk/Re5br8ECcaF0SrsYHNieTabfzxIb/OAyLvVfO0l3WPmwvwV/ppHdFzGGCAtXS7+RY+naqo5xX/iphCdL6YlSyAJwfn7E8h2R0GnkM3HWrpluSgKcZsu+jPVftTOKl/fJ1nYfJUd2rXJ/X6kA/eMSoktUdNxQ3m6WDPwI4q2sxO3WIzOVWh8iCqmXC8GXxN97h4RXKuzDKKKI76gShs4Uu6uC64DSOHqr8rewcRlxBqW10cIBk96ATBCuYjcPRiueMeqx23kAM3GVkY7KJle8ovx7mipEkL2KW2Mpq3Zd8yg12yoEdMo5AajQp1geg1wP3/Tr7jNnnqWSOuWR2RLvGLaayk5+46mkebdfnvonv+AHSc61msZBRbgPgT1YeUzPwBSQU68ithGnS04wQUaB9Rjc54XNsqcKCI+dxdyxxIris+kBrusnLJBRoT+UUxpFl0/hYJP42iL4ECdrwhS4q1XnRNn3LXTP2zkCuBSjyN1NgZJA6VQzbccH/nkzHrst4WU0NvETqs8H/xy+PCZsRhguh5Ly+qWkl5juCFpSK2tQhhUHZpIOE8LoMb3aMY868V3voinX1fNzYDqE4vM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
